import os
import pydicom
from tkinter import *
from tkinter import filedialog

# Main windows setup
mainWindow = Tk()  # Links main window to the interpreter
mainWindow.title("Dicom_Metadata by Kamil_Sokolowski")
mainWindow.geometry("345x235+50+50")  # Window size and initial position
mainWindow['bg'] = 'gray98'  # Background colour

# Main text area
textArea = Text(mainWindow, width=46, height=14, borderwidth=2, bg='old lace')
textArea.place(x=5, y=35)

def openAndProcessDicom():
    # Open Dicom with python dicom package

    textArea.delete("1.0", "end")

    importedFile = filedialog.askopenfilename(initialdir="C:/Users/MainFrame/Desktop/", title="Open Log file",
                                              filetypes=(("Dicom", "*.dcm"),))

    dicomInfo = pydicom.dcmread(importedFile)

    # Create text file output naming structure
    dicomDateTime = dicomInfo.AcquisitionDateTime
    ouputModality = dicomInfo.Modality
    outputName = 'Dicom_Metadata_' + ouputModality + '_'
    dateTimeOutput = dicomDateTime[0:4] + '-' + dicomDateTime[4:6] + '-' + dicomDateTime[6:8] + '_' + dicomDateTime[
                                                                                                      8:12]

    # Initial Pydicom output not a string
    info = str(dicomInfo)

    filePath = os.path.join("~/Desktop")
    fileName = '{0}{1}.txt'.format(outputName, dateTimeOutput)
    expandedFilePath = os.path.expanduser(filePath)
    os.chdir(expandedFilePath)

    # Writes text file
    with open(fileName, 'w') as f:
        for i in info:
            f.write(i)

    textArea.insert(END, 'Dicom metadata output created for: \n' + str(dicomInfo.PatientName) + '\n')
    textArea.insert(END, '\nImported file: \n' + importedFile)
    textArea.insert(END, '\n\nDate of Study:  ' + dateTimeOutput)
    textArea.insert(END, '\n\nExport location: ' + os.getcwd())


def aboutInformation():
    textArea.delete("1.0", "end")
    textArea.insert(END, "Dicom_Metadata\n\nVersion 1.0\n\n25th May 2021\n\nDicom_Metadata generates a text file with all\nthe metadata "
                         "contained with a dicom file.\n\nCopyright (c) 2021 Kamil Sokolowski \n\n"
                         "Source code & license (MIT) available at:\nhttps://github.com/thatKamil/Cubes_ReadEasy")

def useInformation():
    textArea.delete("1.0", "end")
    textArea.insert(END, "\t\t-=Use Guide=-\n\n1. Open Dicom_Metadata and click 'Open File'.\n\n2. The text file will be exported to the \n   desktop."
                         "\n\nThe program can process dicom files generated \nby Molecubes PET & CT machines."
                         "\n\nIt will likely work for data generated by \nMolecubes SPECT and other machines, though this "
                         "hasn't been tested.\n\n")

Button(mainWindow, text="Open File", command=openAndProcessDicom, height=1, width=19,
       bg='snow', font='Courier').place(x=5, y=5)
Button(mainWindow, text="About", command=aboutInformation, height=1, width=6,
       bg='snow', font='Courier').place(x=261, y=5)
Button(mainWindow, text="Guide", command=useInformation, height=1, width=6,
       bg='snow', font='Courier').place(x=186, y=5)

textArea.insert(END,
                '\t       +--------------+\n\t       |.------------.|\n\t       ||Open a Dicom||\n\t       ||file to     ||\n'
                '\t       ||start:      ||\n\t       ||            ||\n\t       |+------------+|\n\t       +-..--------..-+\n'
                '\t       .--------------.\n\t      / /============\ \\ \n\t     / /==============\ \\ \n\t'
                '    /____________________\\ \n\t    \____________________/')


mainWindow.mainloop()